env_name: 'Ant'
gae_lambda: 0.95
gamma: 0.99
clip_coef: 0.2
max_clip_coef: 4
vf_coef: 1
ent_coef: 0.01
max_version: 1000000
use_noise: True
learning_rate: 0.00025
ratio_coef: 0.5
grad_norm: 0.5
pg_loss_type: 2
enable_clip_max: True
enable_ratio_decay: False
enable_entropy_decay: False
enable_lr_decay: False
enable_grad_norm: False
enable_adv_norm: True
enable_mini_batch: True
pae_length: 256
num_envs: 8
num_steps: 512
use_gpu: False
mini_batch_size: 128
